include ../../build-conf/vars.mk
include ../../build-conf/rules.mk

all: bin ucode

.PHONY: ucode

bin: 
	mkdir $(BIN)

ucode: 
#	dotnet run --project ../../microasm/microasm.csproj 10 2 2 2 . bin
# TODO Need to fix hardcoding of overall ROM size