include ../../build-conf/vars.mk
include ../../build-conf/rules.mk

all: ucode

.PHONY: ucode

ucode: 
#	dotnet run --project ../../microasm/microasm.csproj 10 2 2 2 . bin
# TODO Need to fix hardcoding of overall ROM size