include ../../build-conf/vars.mk
include ../../build-conf/rules.mk

TARGETS = bin/mul10.bin bin/multiply.bin bin/RAM.bin bin/square.bin bin/dow.bin

all: bin all-asm

bin: 
	mkdir $(BIN)

all-asm: $(TARGETS)
	